/**
* Generated by LEA for Arma 3
* Version: 2.0.21
* Sun Aug 03 16:54:26 CEST 2014
* Mission file name: TrUebPl_NEU.Chernarus
* Mission name: TrUebPl_NEU.Chernarus
* Required mods:
* + ArmA 3
* + AGM
* + RQ-11B Raven
* + ACRE
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//Empty, nothing to do. unit IED
//Empty, nothing to do. unit marine

/**
* Loadout for soldiers units
*/

