/**
* Generated by LEA for Arma 3
* Version: 2.0.21
* Sun Aug 03 16:54:26 CEST 2014
* Mission file name: TrUebPl_NEU.Chernarus
* Mission name: TrUebPl_NEU.Chernarus
* Required mods:
* + ArmA 3
* + AGM
* + RQ-11B Raven
* + ACRE
* 
* Call the script: _dummy = [] execvm "lea\loadoutServer.sqf";
* 
*/

/**
* Loadout for crates
*/

  clearweaponcargoGlobal BlueInf;
  clearmagazinecargoGlobal BlueInf;
  clearitemcargoGlobal BlueInf;

  BlueInf addweaponcargoGlobal ["arifle_Mk20C_F",20];
  BlueInf addweaponcargoGlobal ["hgun_PDW2000_F",20];
  BlueInf addweaponcargoGlobal ["arifle_MXM_Black_F",20];
  BlueInf addweaponcargoGlobal ["arifle_MX_Black_F",20];
  BlueInf addweaponcargoGlobal ["arifle_MX_GL_Black_F",20];
  BlueInf addweaponcargoGlobal ["arifle_Mk20_GL_F",20];
  BlueInf addweaponcargoGlobal ["arifle_MX_F",20];
  BlueInf addweaponcargoGlobal ["arifle_Mk20_plain_F",20];
  BlueInf addweaponcargoGlobal ["LMG_Mk200_F",20];
  BlueInf addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",20];
  BlueInf addweaponcargoGlobal ["hgun_ACPC2_F",20];
  BlueInf addweaponcargoGlobal ["hgun_Pistol_heavy_01_F",20];
  BlueInf addweaponcargoGlobal ["arifle_Mk20C_plain_F",20];
  BlueInf addweaponcargoGlobal ["SMG_01_F",20];
  BlueInf addweaponcargoGlobal ["SMG_02_F",20];
  BlueInf addweaponcargoGlobal ["arifle_Mk20_GL_plain_F",20];
  BlueInf addweaponcargoGlobal ["arifle_MX_SW_Black_F",20];
  BlueInf addweaponcargoGlobal ["arifle_MXC_F",20];
  BlueInf addweaponcargoGlobal ["arifle_MX_GL_F",20];
  BlueInf addweaponcargoGlobal ["arifle_TRG21_GL_F",20];
  BlueInf addweaponcargoGlobal ["arifle_Mk20_F",20];
  BlueInf addweaponcargoGlobal ["arifle_MXC_Black_F",20];
  BlueInf addweaponcargoGlobal ["arifle_MXM_F",20];
  BlueInf addweaponcargoGlobal ["arifle_MX_SW_F",20];
  BlueInf addweaponcargoGlobal ["srifle_EBR_F",20];
  BlueInf addweaponcargoGlobal ["hgun_P07_F",20];

  clearweaponcargoGlobal BlueWerfer;
  clearmagazinecargoGlobal BlueWerfer;
  clearitemcargoGlobal BlueWerfer;

  BlueWerfer addweaponcargoGlobal ["launch_B_Titan_short_F",30];
  BlueWerfer addweaponcargoGlobal ["launch_NLAW_F",30];
  BlueWerfer addweaponcargoGlobal ["launch_B_Titan_F",30];
  BlueWerfer addmagazinecargoGlobal ["Titan_AT",50];
  BlueWerfer addmagazinecargoGlobal ["NLAW_F",30];
  BlueWerfer addmagazinecargoGlobal ["Titan_AA",50];
  BlueWerfer addmagazinecargoGlobal ["Titan_AP",50];

  clearweaponcargoGlobal BlueSpez;
  clearmagazinecargoGlobal BlueSpez;
  clearitemcargoGlobal BlueSpez;

  BlueSpez addweaponcargoGlobal ["srifle_LRR_F",20];
  BlueSpez addweaponcargoGlobal ["srifle_GM6_F",20];
  BlueSpez addmagazinecargoGlobal ["7Rnd_408_Mag",50];
  BlueSpez addmagazinecargoGlobal ["5Rnd_127x108_Mag",50];

  clearweaponcargoGlobal zeug;
  clearmagazinecargoGlobal zeug;
  clearitemcargoGlobal zeug;

  zeug addmagazinecargoGlobal ["SmokeShellRed",100];
  zeug addmagazinecargoGlobal ["SmokeShellOrange",100];
  zeug addmagazinecargoGlobal ["MiniGrenade",100];
  zeug addmagazinecargoGlobal ["HandGrenade",100];
  zeug addmagazinecargoGlobal ["Laserbatteries",30];
  zeug addmagazinecargoGlobal ["SmokeShellGreen",100];
  zeug addmagazinecargoGlobal ["SmokeShellPurple",100];
  zeug addmagazinecargoGlobal ["SmokeShell",100];
  zeug addmagazinecargoGlobal ["SmokeShellYellow",100];
  zeug addmagazinecargoGlobal ["SmokeShellBlue",100];
  zeug additemcargoGlobal ["AGM_Bandage",200];
  zeug additemcargoGlobal ["Binocular",30];
  zeug additemcargoGlobal ["ItemCompass",30];
  zeug additemcargoGlobal ["Laserdesignator",30];
  zeug additemcargoGlobal ["ItemWatch",30];
  zeug additemcargoGlobal ["MineDetector",30];
  zeug additemcargoGlobal ["AGM_Morphine",100];
  zeug additemcargoGlobal ["ItemGPS",30];
  zeug additemcargoGlobal ["AGM_Bloodbag",100];
  zeug additemcargoGlobal ["AGM_SpareBarrel",30];
  zeug additemcargoGlobal ["AGM_EarBuds",30];
  zeug additemcargoGlobal ["ItemMap",30];
  zeug additemcargoGlobal ["NVGoggles",30];
  zeug additemcargoGlobal ["AGM_Epipen",100];
  zeug additemcargoGlobal ["Rangefinder",30];
  zeug additemcargoGlobal ["Toolkit",10];

  clearweaponcargoGlobal Visiere;
  clearmagazinecargoGlobal Visiere;
  clearitemcargoGlobal Visiere;

  Visiere additemcargoGlobal ["optic_ACO_grn",50];
  Visiere additemcargoGlobal ["muzzle_snds_M",50];
  Visiere additemcargoGlobal ["muzzle_snds_L",50];
  Visiere additemcargoGlobal ["optic_MRD",50];
  Visiere additemcargoGlobal ["optic_Nightstalker",50];
  Visiere additemcargoGlobal ["muzzle_snds_H",50];
  Visiere additemcargoGlobal ["optic_Holosight",50];
  Visiere additemcargoGlobal ["optic_SOS",50];
  Visiere additemcargoGlobal ["optic_MRCO",50];
  Visiere additemcargoGlobal ["optic_Holosight_smg",50];
  Visiere additemcargoGlobal ["optic_tws",50];
  Visiere additemcargoGlobal ["optic_NVS",50];
  Visiere additemcargoGlobal ["muzzle_snds_B",50];
  Visiere additemcargoGlobal ["muzzle_snds_acp",50];
  Visiere additemcargoGlobal ["acc_flashlight",50];
  Visiere additemcargoGlobal ["optic_Arco",50];
  Visiere additemcargoGlobal ["optic_Yorris",50];
  Visiere additemcargoGlobal ["muzzle_snds_H_MG",50];
  Visiere additemcargoGlobal ["optic_Aco_smg",50];
  Visiere additemcargoGlobal ["optic_Aco",50];
  Visiere additemcargoGlobal ["optic_DMS",50];
  Visiere additemcargoGlobal ["optic_LRPS",50];
  Visiere additemcargoGlobal ["acc_pointer_IR",50];
  Visiere additemcargoGlobal ["optic_Hamr",50];
  Visiere additemcargoGlobal ["optic_ACO_grn_smg",50];
  Visiere additemcargoGlobal ["optic_tws_mg",50];

  clearweaponcargoGlobal BlueInfMun;
  clearmagazinecargoGlobal BlueInfMun;
  clearitemcargoGlobal BlueInfMun;

  BlueInfMun addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",100];
  BlueInfMun addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",50];
  BlueInfMun addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",100];
  BlueInfMun addmagazinecargoGlobal ["20Rnd_762x51_Mag",100];
  BlueInfMun addmagazinecargoGlobal ["30Rnd_556x45_Stanag",100];
  BlueInfMun addmagazinecargoGlobal ["100Rnd_65x39_caseless_mag_Tracer",50];
  BlueInfMun addmagazinecargoGlobal ["1Rnd_SmokeOrange_Grenade_shell",50];
  BlueInfMun addmagazinecargoGlobal ["1Rnd_Smoke_Grenade_shell",50];
  BlueInfMun addmagazinecargoGlobal ["1Rnd_SmokeBlue_Grenade_shell",50];
  BlueInfMun addmagazinecargoGlobal ["30Rnd_9x21_Mag",50];
  BlueInfMun addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",50];
  BlueInfMun addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",50];
  BlueInfMun addmagazinecargoGlobal ["1Rnd_SmokePurple_Grenade_shell",50];
  BlueInfMun addmagazinecargoGlobal ["100Rnd_65x39_caseless_mag",100];
  BlueInfMun addmagazinecargoGlobal ["1Rnd_SmokeYellow_Grenade_shell",50];
  BlueInfMun addmagazinecargoGlobal ["11Rnd_45ACP_Mag",50];
  BlueInfMun addmagazinecargoGlobal ["30Rnd_556x45_Stanag_Tracer_Red",100];
  BlueInfMun addmagazinecargoGlobal ["16Rnd_9x21_Mag",50];
  BlueInfMun addmagazinecargoGlobal ["9Rnd_45ACP_Mag",50];
  BlueInfMun addmagazinecargoGlobal ["200Rnd_65x39_cased_Box",50];
  BlueInfMun addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",100];
  BlueInfMun addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",50];

  clearweaponcargoGlobal ruck;
  clearmagazinecargoGlobal ruck;
  clearitemcargoGlobal ruck;

  ruck addBackpackCargoGlobal ["B_OutdoorPack_blk",15];
  ruck addBackpackCargoGlobal ["B_MAV_B_BACKPACK",4];
  ruck addBackpackCargoGlobal ["B_TacticalPack_blk",15];

  clearweaponcargoGlobal funk;
  clearmagazinecargoGlobal funk;
  clearitemcargoGlobal funk;

  funk additemcargoGlobal ["ACRE_PRC117F",20];
  funk additemcargoGlobal ["ACRE_PRC148",20];
  funk additemcargoGlobal ["ACRE_PRC148_UHF",20];
  funk additemcargoGlobal ["ACRE_PRC343",20];
  funk additemcargoGlobal ["ACRE_PRC152",20];
  funk additemcargoGlobal ["ACRE_PRC119",20];

  clearweaponcargoGlobal Spreng;
  clearmagazinecargoGlobal Spreng;
  clearitemcargoGlobal Spreng;

  Spreng addmagazinecargoGlobal ["APERSMine_Range_Mag",20];
  Spreng addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",20];
  Spreng addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",20];
  Spreng addmagazinecargoGlobal ["ClaymoreDirectionalMine_Remote_Mag",20];
  Spreng addmagazinecargoGlobal ["HandGrenade",20];
  Spreng addmagazinecargoGlobal ["DemoCharge_Remote_Mag",20];
  Spreng addmagazinecargoGlobal ["APERSBoundingMine_Range_Mag",20];
  Spreng addmagazinecargoGlobal ["ATMine_Range_Mag",20];
  Spreng addmagazinecargoGlobal ["SLAMDirectionalMine_Wire_Mag",20];

  clearweaponcargoGlobal BlueInf_1;
  clearmagazinecargoGlobal BlueInf_1;
  clearitemcargoGlobal BlueInf_1;

  BlueInf_1 addweaponcargoGlobal ["SMG_01_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_Mk20C_F",20];
  BlueInf_1 addweaponcargoGlobal ["SMG_02_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_Mk20_GL_plain_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_MX_SW_Black_F",20];
  BlueInf_1 addweaponcargoGlobal ["hgun_PDW2000_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_MXM_Black_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_MXC_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_MX_GL_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_TRG21_GL_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_MX_Black_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_MX_GL_Black_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_Mk20_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_MXC_Black_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_MXM_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_MX_SW_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_Mk20_GL_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_MX_F",20];
  BlueInf_1 addweaponcargoGlobal ["srifle_EBR_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_Mk20_plain_F",20];
  BlueInf_1 addweaponcargoGlobal ["LMG_Mk200_F",20];
  BlueInf_1 addweaponcargoGlobal ["arifle_Mk20C_plain_F",20];

  clearweaponcargoGlobal BlueSpez_1;
  clearmagazinecargoGlobal BlueSpez_1;
  clearitemcargoGlobal BlueSpez_1;

  BlueSpez_1 addweaponcargoGlobal ["srifle_LRR_F",20];
  BlueSpez_1 addweaponcargoGlobal ["srifle_GM6_F",20];
  BlueSpez_1 addmagazinecargoGlobal ["7Rnd_408_Mag",50];
  BlueSpez_1 addmagazinecargoGlobal ["5Rnd_127x108_Mag",50];

  clearweaponcargoGlobal BlueInfMun_1;
  clearmagazinecargoGlobal BlueInfMun_1;
  clearitemcargoGlobal BlueInfMun_1;

  BlueInfMun_1 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",100];
  BlueInfMun_1 addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",50];
  BlueInfMun_1 addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",100];
  BlueInfMun_1 addmagazinecargoGlobal ["20Rnd_762x51_Mag",100];
  BlueInfMun_1 addmagazinecargoGlobal ["30Rnd_556x45_Stanag",100];
  BlueInfMun_1 addmagazinecargoGlobal ["100Rnd_65x39_caseless_mag_Tracer",50];
  BlueInfMun_1 addmagazinecargoGlobal ["1Rnd_SmokeOrange_Grenade_shell",50];
  BlueInfMun_1 addmagazinecargoGlobal ["1Rnd_Smoke_Grenade_shell",50];
  BlueInfMun_1 addmagazinecargoGlobal ["1Rnd_SmokeBlue_Grenade_shell",50];
  BlueInfMun_1 addmagazinecargoGlobal ["30Rnd_9x21_Mag",50];
  BlueInfMun_1 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",50];
  BlueInfMun_1 addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",50];
  BlueInfMun_1 addmagazinecargoGlobal ["1Rnd_SmokePurple_Grenade_shell",50];
  BlueInfMun_1 addmagazinecargoGlobal ["100Rnd_65x39_caseless_mag",100];
  BlueInfMun_1 addmagazinecargoGlobal ["1Rnd_SmokeYellow_Grenade_shell",50];
  BlueInfMun_1 addmagazinecargoGlobal ["11Rnd_45ACP_Mag",50];
  BlueInfMun_1 addmagazinecargoGlobal ["30Rnd_556x45_Stanag_Tracer_Red",100];
  BlueInfMun_1 addmagazinecargoGlobal ["16Rnd_9x21_Mag",50];
  BlueInfMun_1 addmagazinecargoGlobal ["9Rnd_45ACP_Mag",50];
  BlueInfMun_1 addmagazinecargoGlobal ["200Rnd_65x39_cased_Box",50];
  BlueInfMun_1 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",100];
  BlueInfMun_1 addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",50];

  clearweaponcargoGlobal BlueWerfer_1;
  clearmagazinecargoGlobal BlueWerfer_1;
  clearitemcargoGlobal BlueWerfer_1;

  BlueWerfer_1 addweaponcargoGlobal ["launch_B_Titan_short_F",30];
  BlueWerfer_1 addweaponcargoGlobal ["launch_NLAW_F",30];
  BlueWerfer_1 addweaponcargoGlobal ["launch_B_Titan_F",30];
  BlueWerfer_1 addmagazinecargoGlobal ["Titan_AT",50];
  BlueWerfer_1 addmagazinecargoGlobal ["NLAW_F",30];
  BlueWerfer_1 addmagazinecargoGlobal ["Titan_AA",50];
  BlueWerfer_1 addmagazinecargoGlobal ["Titan_AP",50];

  clearweaponcargoGlobal Visiere_1;
  clearmagazinecargoGlobal Visiere_1;
  clearitemcargoGlobal Visiere_1;

  Visiere_1 additemcargoGlobal ["optic_ACO_grn",50];
  Visiere_1 additemcargoGlobal ["muzzle_snds_M",50];
  Visiere_1 additemcargoGlobal ["muzzle_snds_L",50];
  Visiere_1 additemcargoGlobal ["optic_MRD",50];
  Visiere_1 additemcargoGlobal ["optic_Nightstalker",50];
  Visiere_1 additemcargoGlobal ["muzzle_snds_H",50];
  Visiere_1 additemcargoGlobal ["optic_Holosight",50];
  Visiere_1 additemcargoGlobal ["optic_SOS",50];
  Visiere_1 additemcargoGlobal ["optic_MRCO",50];
  Visiere_1 additemcargoGlobal ["optic_Holosight_smg",50];
  Visiere_1 additemcargoGlobal ["optic_tws",50];
  Visiere_1 additemcargoGlobal ["optic_NVS",50];
  Visiere_1 additemcargoGlobal ["muzzle_snds_B",50];
  Visiere_1 additemcargoGlobal ["muzzle_snds_acp",50];
  Visiere_1 additemcargoGlobal ["acc_flashlight",50];
  Visiere_1 additemcargoGlobal ["optic_Arco",50];
  Visiere_1 additemcargoGlobal ["optic_Yorris",50];
  Visiere_1 additemcargoGlobal ["muzzle_snds_H_MG",50];
  Visiere_1 additemcargoGlobal ["optic_Aco_smg",50];
  Visiere_1 additemcargoGlobal ["optic_Aco",50];
  Visiere_1 additemcargoGlobal ["optic_DMS",50];
  Visiere_1 additemcargoGlobal ["optic_LRPS",50];
  Visiere_1 additemcargoGlobal ["acc_pointer_IR",50];
  Visiere_1 additemcargoGlobal ["optic_Hamr",50];
  Visiere_1 additemcargoGlobal ["optic_ACO_grn_smg",50];
  Visiere_1 additemcargoGlobal ["optic_tws_mg",50];

//Empty, nothing to do. unit IED
  clearweaponcargoGlobal BlueInf_1_1;
  clearmagazinecargoGlobal BlueInf_1_1;
  clearitemcargoGlobal BlueInf_1_1;

  BlueInf_1_1 addweaponcargoGlobal ["SMG_01_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_Mk20C_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["SMG_02_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_Mk20_GL_plain_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_MX_SW_Black_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["hgun_PDW2000_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_MXM_Black_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_MXC_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_MX_GL_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_TRG21_GL_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_MX_Black_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_MX_GL_Black_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_Mk20_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_MXC_Black_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_MXM_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_MX_SW_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_Mk20_GL_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_MX_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["srifle_EBR_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_Mk20_plain_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["LMG_Mk200_F",20];
  BlueInf_1_1 addweaponcargoGlobal ["arifle_Mk20C_plain_F",20];

  clearweaponcargoGlobal BlueSpez_1_1;
  clearmagazinecargoGlobal BlueSpez_1_1;
  clearitemcargoGlobal BlueSpez_1_1;

  BlueSpez_1_1 addweaponcargoGlobal ["srifle_LRR_F",20];
  BlueSpez_1_1 addweaponcargoGlobal ["srifle_GM6_F",20];
  BlueSpez_1_1 addmagazinecargoGlobal ["7Rnd_408_Mag",50];
  BlueSpez_1_1 addmagazinecargoGlobal ["5Rnd_127x108_Mag",50];

  clearweaponcargoGlobal BlueInfMun_1_1;
  clearmagazinecargoGlobal BlueInfMun_1_1;
  clearitemcargoGlobal BlueInfMun_1_1;

  BlueInfMun_1_1 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",100];
  BlueInfMun_1_1 addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",100];
  BlueInfMun_1_1 addmagazinecargoGlobal ["20Rnd_762x51_Mag",100];
  BlueInfMun_1_1 addmagazinecargoGlobal ["30Rnd_556x45_Stanag",100];
  BlueInfMun_1_1 addmagazinecargoGlobal ["100Rnd_65x39_caseless_mag_Tracer",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["1Rnd_SmokeOrange_Grenade_shell",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["1Rnd_Smoke_Grenade_shell",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["1Rnd_SmokeBlue_Grenade_shell",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["30Rnd_9x21_Mag",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["1Rnd_SmokePurple_Grenade_shell",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["100Rnd_65x39_caseless_mag",100];
  BlueInfMun_1_1 addmagazinecargoGlobal ["1Rnd_SmokeYellow_Grenade_shell",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["11Rnd_45ACP_Mag",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["30Rnd_556x45_Stanag_Tracer_Red",100];
  BlueInfMun_1_1 addmagazinecargoGlobal ["16Rnd_9x21_Mag",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["9Rnd_45ACP_Mag",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["200Rnd_65x39_cased_Box",50];
  BlueInfMun_1_1 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",100];
  BlueInfMun_1_1 addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",50];

  clearweaponcargoGlobal Visiere_1_1;
  clearmagazinecargoGlobal Visiere_1_1;
  clearitemcargoGlobal Visiere_1_1;

  Visiere_1_1 additemcargoGlobal ["optic_ACO_grn",50];
  Visiere_1_1 additemcargoGlobal ["muzzle_snds_M",50];
  Visiere_1_1 additemcargoGlobal ["muzzle_snds_L",50];
  Visiere_1_1 additemcargoGlobal ["optic_MRD",50];
  Visiere_1_1 additemcargoGlobal ["optic_Nightstalker",50];
  Visiere_1_1 additemcargoGlobal ["muzzle_snds_H",50];
  Visiere_1_1 additemcargoGlobal ["optic_Holosight",50];
  Visiere_1_1 additemcargoGlobal ["optic_SOS",50];
  Visiere_1_1 additemcargoGlobal ["optic_MRCO",50];
  Visiere_1_1 additemcargoGlobal ["optic_Holosight_smg",50];
  Visiere_1_1 additemcargoGlobal ["optic_tws",50];
  Visiere_1_1 additemcargoGlobal ["optic_NVS",50];
  Visiere_1_1 additemcargoGlobal ["muzzle_snds_B",50];
  Visiere_1_1 additemcargoGlobal ["muzzle_snds_acp",50];
  Visiere_1_1 additemcargoGlobal ["acc_flashlight",50];
  Visiere_1_1 additemcargoGlobal ["optic_Arco",50];
  Visiere_1_1 additemcargoGlobal ["optic_Yorris",50];
  Visiere_1_1 additemcargoGlobal ["muzzle_snds_H_MG",50];
  Visiere_1_1 additemcargoGlobal ["optic_Aco_smg",50];
  Visiere_1_1 additemcargoGlobal ["optic_Aco",50];
  Visiere_1_1 additemcargoGlobal ["optic_DMS",50];
  Visiere_1_1 additemcargoGlobal ["optic_LRPS",50];
  Visiere_1_1 additemcargoGlobal ["acc_pointer_IR",50];
  Visiere_1_1 additemcargoGlobal ["optic_Hamr",50];
  Visiere_1_1 additemcargoGlobal ["optic_ACO_grn_smg",50];
  Visiere_1_1 additemcargoGlobal ["optic_tws_mg",50];

  clearweaponcargoGlobal BlueInf_1_2;
  clearmagazinecargoGlobal BlueInf_1_2;
  clearitemcargoGlobal BlueInf_1_2;

  BlueInf_1_2 addweaponcargoGlobal ["SMG_01_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_Mk20C_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["SMG_02_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_Mk20_GL_plain_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_MX_SW_Black_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["hgun_PDW2000_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_MXM_Black_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_MXC_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_MX_GL_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_TRG21_GL_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_MX_Black_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_MX_GL_Black_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_Mk20_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_MXC_Black_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_MXM_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_MX_SW_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_Mk20_GL_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_MX_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["srifle_EBR_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_Mk20_plain_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["LMG_Mk200_F",20];
  BlueInf_1_2 addweaponcargoGlobal ["arifle_Mk20C_plain_F",20];

  clearweaponcargoGlobal BlueSpez_1_2;
  clearmagazinecargoGlobal BlueSpez_1_2;
  clearitemcargoGlobal BlueSpez_1_2;

  BlueSpez_1_2 addweaponcargoGlobal ["srifle_LRR_F",20];
  BlueSpez_1_2 addweaponcargoGlobal ["srifle_GM6_F",20];
  BlueSpez_1_2 addmagazinecargoGlobal ["7Rnd_408_Mag",50];
  BlueSpez_1_2 addmagazinecargoGlobal ["5Rnd_127x108_Mag",50];

  clearweaponcargoGlobal BlueInfMun_1_2;
  clearmagazinecargoGlobal BlueInfMun_1_2;
  clearitemcargoGlobal BlueInfMun_1_2;

  BlueInfMun_1_2 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",100];
  BlueInfMun_1_2 addmagazinecargoGlobal ["1Rnd_SmokeGreen_Grenade_shell",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",100];
  BlueInfMun_1_2 addmagazinecargoGlobal ["20Rnd_762x51_Mag",100];
  BlueInfMun_1_2 addmagazinecargoGlobal ["30Rnd_556x45_Stanag",100];
  BlueInfMun_1_2 addmagazinecargoGlobal ["100Rnd_65x39_caseless_mag_Tracer",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["1Rnd_SmokeOrange_Grenade_shell",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["1Rnd_Smoke_Grenade_shell",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["1Rnd_SmokeBlue_Grenade_shell",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["30Rnd_9x21_Mag",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["1Rnd_SmokeRed_Grenade_shell",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["1Rnd_SmokePurple_Grenade_shell",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["100Rnd_65x39_caseless_mag",100];
  BlueInfMun_1_2 addmagazinecargoGlobal ["1Rnd_SmokeYellow_Grenade_shell",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["11Rnd_45ACP_Mag",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["30Rnd_556x45_Stanag_Tracer_Red",100];
  BlueInfMun_1_2 addmagazinecargoGlobal ["16Rnd_9x21_Mag",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["9Rnd_45ACP_Mag",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["200Rnd_65x39_cased_Box",50];
  BlueInfMun_1_2 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag_Tracer",100];
  BlueInfMun_1_2 addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",50];

  clearweaponcargoGlobal Visiere_1_2;
  clearmagazinecargoGlobal Visiere_1_2;
  clearitemcargoGlobal Visiere_1_2;

  Visiere_1_2 additemcargoGlobal ["optic_ACO_grn",50];
  Visiere_1_2 additemcargoGlobal ["muzzle_snds_M",50];
  Visiere_1_2 additemcargoGlobal ["muzzle_snds_L",50];
  Visiere_1_2 additemcargoGlobal ["optic_MRD",50];
  Visiere_1_2 additemcargoGlobal ["optic_Nightstalker",50];
  Visiere_1_2 additemcargoGlobal ["muzzle_snds_H",50];
  Visiere_1_2 additemcargoGlobal ["optic_Holosight",50];
  Visiere_1_2 additemcargoGlobal ["optic_SOS",50];
  Visiere_1_2 additemcargoGlobal ["optic_MRCO",50];
  Visiere_1_2 additemcargoGlobal ["optic_Holosight_smg",50];
  Visiere_1_2 additemcargoGlobal ["optic_tws",50];
  Visiere_1_2 additemcargoGlobal ["optic_NVS",50];
  Visiere_1_2 additemcargoGlobal ["muzzle_snds_B",50];
  Visiere_1_2 additemcargoGlobal ["muzzle_snds_acp",50];
  Visiere_1_2 additemcargoGlobal ["acc_flashlight",50];
  Visiere_1_2 additemcargoGlobal ["optic_Arco",50];
  Visiere_1_2 additemcargoGlobal ["optic_Yorris",50];
  Visiere_1_2 additemcargoGlobal ["muzzle_snds_H_MG",50];
  Visiere_1_2 additemcargoGlobal ["optic_Aco_smg",50];
  Visiere_1_2 additemcargoGlobal ["optic_Aco",50];
  Visiere_1_2 additemcargoGlobal ["optic_DMS",50];
  Visiere_1_2 additemcargoGlobal ["optic_LRPS",50];
  Visiere_1_2 additemcargoGlobal ["acc_pointer_IR",50];
  Visiere_1_2 additemcargoGlobal ["optic_Hamr",50];
  Visiere_1_2 additemcargoGlobal ["optic_ACO_grn_smg",50];
  Visiere_1_2 additemcargoGlobal ["optic_tws_mg",50];

//Empty, nothing to do. unit marine
  clearweaponcargoGlobal marineaus;
  clearmagazinecargoGlobal marineaus;
  clearitemcargoGlobal marineaus;

  marineaus addweaponcargoGlobal ["arifle_SDAR_F",5];
  marineaus addmagazinecargoGlobal ["20Rnd_556x45_UW_mag",20];
  marineaus additemcargoGlobal ["G_Diving",5];
  marineaus addItemCargoGlobal ["V_RebreatherB",5];
  marineaus addItemCargoGlobal ["U_B_Wetsuit",5];

  clearweaponcargoGlobal leuchtmittel2;
  clearmagazinecargoGlobal leuchtmittel2;
  clearitemcargoGlobal leuchtmittel2;

  leuchtmittel2 addmagazinecargoGlobal ["UGL_FlareWhite_F",20];
  leuchtmittel2 addmagazinecargoGlobal ["UGL_FlareRed_F",20];
  leuchtmittel2 addmagazinecargoGlobal ["UGL_FlareCIR_F",20];
  leuchtmittel2 addmagazinecargoGlobal ["UGL_FlareGreen_F",20];
  leuchtmittel2 addmagazinecargoGlobal ["UGL_FlareYellow_F",20];

  clearweaponcargoGlobal leuchtmittel1;
  clearmagazinecargoGlobal leuchtmittel1;
  clearitemcargoGlobal leuchtmittel1;

  leuchtmittel1 addmagazinecargoGlobal ["UGL_FlareWhite_F",20];
  leuchtmittel1 addmagazinecargoGlobal ["UGL_FlareRed_F",20];
  leuchtmittel1 addmagazinecargoGlobal ["UGL_FlareCIR_F",20];
  leuchtmittel1 addmagazinecargoGlobal ["UGL_FlareGreen_F",20];
  leuchtmittel1 addmagazinecargoGlobal ["UGL_FlareYellow_F",20];


/**
* Loadout for soldiers units
*/

if (!isNil "sprengpl") then {
removeallweapons sprengpl;
removeallassigneditems sprengpl;
removeBackpack sprengpl;
removeVest sprengpl;
removeHeadgear sprengpl;
removeUniform sprengpl;
removeGoggles sprengpl;

if (count weapons sprengpl > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons sprengpl) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     sprengpl selectWeapon (_muzzles select 0);
  }
  else {
     sprengpl selectWeapon _type;
  };
};
};

if (!isNil "base") then {
removeallweapons base;
removeallassigneditems base;
removeBackpack base;
removeVest base;
removeHeadgear base;
removeUniform base;
removeGoggles base;

if (count weapons base > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons base) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     base selectWeapon (_muzzles select 0);
  }
  else {
     base selectWeapon _type;
  };
};
};

if (!isNil "infsch") then {
removeallweapons infsch;
removeallassigneditems infsch;
removeBackpack infsch;
removeVest infsch;
removeHeadgear infsch;
removeUniform infsch;
removeGoggles infsch;

if (count weapons infsch > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons infsch) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     infsch selectWeapon (_muzzles select 0);
  }
  else {
     infsch selectWeapon _type;
  };
};
};

if (!isNil "werfer") then {
removeallweapons werfer;
removeallassigneditems werfer;
removeBackpack werfer;
removeVest werfer;
removeHeadgear werfer;
removeUniform werfer;
removeGoggles werfer;

if (count weapons werfer > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons werfer) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     werfer selectWeapon (_muzzles select 0);
  }
  else {
     werfer selectWeapon _type;
  };
};
};

if (!isNil "T14") then {
removeallweapons T14;
removeallassigneditems T14;
removeBackpack T14;
removeVest T14;
removeHeadgear T14;
removeUniform T14;
removeGoggles T14;

if (count weapons T14 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T14) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T14 selectWeapon (_muzzles select 0);
  }
  else {
     T14 selectWeapon _type;
  };
};
};

if (!isNil "Tab2") then {
removeallweapons Tab2;
removeallassigneditems Tab2;
removeBackpack Tab2;
removeVest Tab2;
removeHeadgear Tab2;
removeUniform Tab2;
removeGoggles Tab2;

if (count weapons Tab2 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Tab2) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Tab2 selectWeapon (_muzzles select 0);
  }
  else {
     Tab2 selectWeapon _type;
  };
};
};

if (!isNil "T15") then {
removeallweapons T15;
removeallassigneditems T15;
removeBackpack T15;
removeVest T15;
removeHeadgear T15;
removeUniform T15;
removeGoggles T15;

if (count weapons T15 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T15) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T15 selectWeapon (_muzzles select 0);
  }
  else {
     T15 selectWeapon _type;
  };
};
};

if (!isNil "T16") then {
removeallweapons T16;
removeallassigneditems T16;
removeBackpack T16;
removeVest T16;
removeHeadgear T16;
removeUniform T16;
removeGoggles T16;

if (count weapons T16 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T16) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T16 selectWeapon (_muzzles select 0);
  }
  else {
     T16 selectWeapon _type;
  };
};
};

if (!isNil "T19") then {
removeallweapons T19;
removeallassigneditems T19;
removeBackpack T19;
removeVest T19;
removeHeadgear T19;
removeUniform T19;
removeGoggles T19;

if (count weapons T19 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T19) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T19 selectWeapon (_muzzles select 0);
  }
  else {
     T19 selectWeapon _type;
  };
};
};

if (!isNil "T18") then {
removeallweapons T18;
removeallassigneditems T18;
removeBackpack T18;
removeVest T18;
removeHeadgear T18;
removeUniform T18;
removeGoggles T18;

if (count weapons T18 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T18) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T18 selectWeapon (_muzzles select 0);
  }
  else {
     T18 selectWeapon _type;
  };
};
};

if (!isNil "T17") then {
removeallweapons T17;
removeallassigneditems T17;
removeBackpack T17;
removeVest T17;
removeHeadgear T17;
removeUniform T17;
removeGoggles T17;

if (count weapons T17 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T17) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T17 selectWeapon (_muzzles select 0);
  }
  else {
     T17 selectWeapon _type;
  };
};
};

if (!isNil "Tab") then {
removeallweapons Tab;
removeallassigneditems Tab;
removeBackpack Tab;
removeVest Tab;
removeHeadgear Tab;
removeUniform Tab;
removeGoggles Tab;

if (count weapons Tab > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Tab) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Tab selectWeapon (_muzzles select 0);
  }
  else {
     Tab selectWeapon _type;
  };
};
};

if (!isNil "T13") then {
removeallweapons T13;
removeallassigneditems T13;
removeBackpack T13;
removeVest T13;
removeHeadgear T13;
removeUniform T13;
removeGoggles T13;

if (count weapons T13 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T13) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T13 selectWeapon (_muzzles select 0);
  }
  else {
     T13 selectWeapon _type;
  };
};
};

if (!isNil "T11") then {
removeallweapons T11;
removeallassigneditems T11;
removeBackpack T11;
removeVest T11;
removeHeadgear T11;
removeUniform T11;
removeGoggles T11;

if (count weapons T11 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T11) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T11 selectWeapon (_muzzles select 0);
  }
  else {
     T11 selectWeapon _type;
  };
};
};

if (!isNil "T6") then {
removeallweapons T6;
removeallassigneditems T6;
removeBackpack T6;
removeVest T6;
removeHeadgear T6;
removeUniform T6;
removeGoggles T6;

if (count weapons T6 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T6) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T6 selectWeapon (_muzzles select 0);
  }
  else {
     T6 selectWeapon _type;
  };
};
};

if (!isNil "T5") then {
removeallweapons T5;
removeallassigneditems T5;
removeBackpack T5;
removeVest T5;
removeHeadgear T5;
removeUniform T5;
removeGoggles T5;

if (count weapons T5 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T5) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T5 selectWeapon (_muzzles select 0);
  }
  else {
     T5 selectWeapon _type;
  };
};
};

if (!isNil "T20") then {
removeallweapons T20;
removeallassigneditems T20;
removeBackpack T20;
removeVest T20;
removeHeadgear T20;
removeUniform T20;
removeGoggles T20;

if (count weapons T20 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T20) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T20 selectWeapon (_muzzles select 0);
  }
  else {
     T20 selectWeapon _type;
  };
};
};

if (!isNil "T21") then {
removeallweapons T21;
removeallassigneditems T21;
removeBackpack T21;
removeVest T21;
removeHeadgear T21;
removeUniform T21;
removeGoggles T21;

if (count weapons T21 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T21) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T21 selectWeapon (_muzzles select 0);
  }
  else {
     T21 selectWeapon _type;
  };
};
};

if (!isNil "Tab3") then {
removeallweapons Tab3;
removeallassigneditems Tab3;
removeBackpack Tab3;
removeVest Tab3;
removeHeadgear Tab3;
removeUniform Tab3;
removeGoggles Tab3;

if (count weapons Tab3 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Tab3) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Tab3 selectWeapon (_muzzles select 0);
  }
  else {
     Tab3 selectWeapon _type;
  };
};
};

if (!isNil "T2") then {
removeallweapons T2;
removeallassigneditems T2;
removeBackpack T2;
removeVest T2;
removeHeadgear T2;
removeUniform T2;
removeGoggles T2;

if (count weapons T2 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T2) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T2 selectWeapon (_muzzles select 0);
  }
  else {
     T2 selectWeapon _type;
  };
};
};

if (!isNil "T3") then {
removeallweapons T3;
removeallassigneditems T3;
removeBackpack T3;
removeVest T3;
removeHeadgear T3;
removeUniform T3;
removeGoggles T3;

if (count weapons T3 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T3) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T3 selectWeapon (_muzzles select 0);
  }
  else {
     T3 selectWeapon _type;
  };
};
};

if (!isNil "T4") then {
removeallweapons T4;
removeallassigneditems T4;
removeBackpack T4;
removeVest T4;
removeHeadgear T4;
removeUniform T4;
removeGoggles T4;

if (count weapons T4 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T4) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T4 selectWeapon (_muzzles select 0);
  }
  else {
     T4 selectWeapon _type;
  };
};
};

if (!isNil "T1") then {
removeallweapons T1;
removeallassigneditems T1;
removeBackpack T1;
removeVest T1;
removeHeadgear T1;
removeUniform T1;
removeGoggles T1;

if (count weapons T1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T1 selectWeapon (_muzzles select 0);
  }
  else {
     T1 selectWeapon _type;
  };
};
};

if (!isNil "T23") then {
removeallweapons T23;
removeallassigneditems T23;
removeBackpack T23;
removeVest T23;
removeHeadgear T23;
removeUniform T23;
removeGoggles T23;

if (count weapons T23 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T23) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T23 selectWeapon (_muzzles select 0);
  }
  else {
     T23 selectWeapon _type;
  };
};
};

if (!isNil "T22") then {
removeallweapons T22;
removeallassigneditems T22;
removeBackpack T22;
removeVest T22;
removeHeadgear T22;
removeUniform T22;
removeGoggles T22;

if (count weapons T22 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T22) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T22 selectWeapon (_muzzles select 0);
  }
  else {
     T22 selectWeapon _type;
  };
};
};

if (!isNil "T25") then {
removeallweapons T25;
removeallassigneditems T25;
removeBackpack T25;
removeVest T25;
removeHeadgear T25;
removeUniform T25;
removeGoggles T25;

if (count weapons T25 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T25) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T25 selectWeapon (_muzzles select 0);
  }
  else {
     T25 selectWeapon _type;
  };
};
};

if (!isNil "T24") then {
removeallweapons T24;
removeallassigneditems T24;
removeBackpack T24;
removeVest T24;
removeHeadgear T24;
removeUniform T24;
removeGoggles T24;

if (count weapons T24 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T24) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T24 selectWeapon (_muzzles select 0);
  }
  else {
     T24 selectWeapon _type;
  };
};
};

if (!isNil "T10") then {
removeallweapons T10;
removeallassigneditems T10;
removeBackpack T10;
removeVest T10;
removeHeadgear T10;
removeUniform T10;
removeGoggles T10;

if (count weapons T10 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T10) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T10 selectWeapon (_muzzles select 0);
  }
  else {
     T10 selectWeapon _type;
  };
};
};

if (!isNil "T9") then {
removeallweapons T9;
removeallassigneditems T9;
removeBackpack T9;
removeVest T9;
removeHeadgear T9;
removeUniform T9;
removeGoggles T9;

if (count weapons T9 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T9) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T9 selectWeapon (_muzzles select 0);
  }
  else {
     T9 selectWeapon _type;
  };
};
};

if (!isNil "T7") then {
removeallweapons T7;
removeallassigneditems T7;
removeBackpack T7;
removeVest T7;
removeHeadgear T7;
removeUniform T7;
removeGoggles T7;

if (count weapons T7 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T7) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T7 selectWeapon (_muzzles select 0);
  }
  else {
     T7 selectWeapon _type;
  };
};
};

if (!isNil "T8") then {
removeallweapons T8;
removeallassigneditems T8;
removeBackpack T8;
removeVest T8;
removeHeadgear T8;
removeUniform T8;
removeGoggles T8;

if (count weapons T8 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T8) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T8 selectWeapon (_muzzles select 0);
  }
  else {
     T8 selectWeapon _type;
  };
};
};

if (!isNil "T12") then {
removeallweapons T12;
removeallassigneditems T12;
removeBackpack T12;
removeVest T12;
removeHeadgear T12;
removeUniform T12;
removeGoggles T12;

if (count weapons T12 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons T12) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     T12 selectWeapon (_muzzles select 0);
  }
  else {
     T12 selectWeapon _type;
  };
};
};

if (!isNil "Z4") then {
removeallweapons Z4;
removeallassigneditems Z4;
removeBackpack Z4;
removeVest Z4;
removeHeadgear Z4;
removeUniform Z4;
removeGoggles Z4;

if (count weapons Z4 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z4) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z4 selectWeapon (_muzzles select 0);
  }
  else {
     Z4 selectWeapon _type;
  };
};
};

if (!isNil "Z5") then {
removeallweapons Z5;
removeallassigneditems Z5;
removeBackpack Z5;
removeVest Z5;
removeHeadgear Z5;
removeUniform Z5;
removeGoggles Z5;

if (count weapons Z5 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z5) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z5 selectWeapon (_muzzles select 0);
  }
  else {
     Z5 selectWeapon _type;
  };
};
};

if (!isNil "Z3") then {
removeallweapons Z3;
removeallassigneditems Z3;
removeBackpack Z3;
removeVest Z3;
removeHeadgear Z3;
removeUniform Z3;
removeGoggles Z3;

if (count weapons Z3 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z3) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z3 selectWeapon (_muzzles select 0);
  }
  else {
     Z3 selectWeapon _type;
  };
};
};

if (!isNil "Z12") then {
removeallweapons Z12;
removeallassigneditems Z12;
removeBackpack Z12;
removeVest Z12;
removeHeadgear Z12;
removeUniform Z12;
removeGoggles Z12;

if (count weapons Z12 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z12) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z12 selectWeapon (_muzzles select 0);
  }
  else {
     Z12 selectWeapon _type;
  };
};
};

if (!isNil "Z2") then {
removeallweapons Z2;
removeallassigneditems Z2;
removeBackpack Z2;
removeVest Z2;
removeHeadgear Z2;
removeUniform Z2;
removeGoggles Z2;

if (count weapons Z2 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z2) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z2 selectWeapon (_muzzles select 0);
  }
  else {
     Z2 selectWeapon _type;
  };
};
};

if (!isNil "Z11") then {
removeallweapons Z11;
removeallassigneditems Z11;
removeBackpack Z11;
removeVest Z11;
removeHeadgear Z11;
removeUniform Z11;
removeGoggles Z11;

if (count weapons Z11 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z11) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z11 selectWeapon (_muzzles select 0);
  }
  else {
     Z11 selectWeapon _type;
  };
};
};

if (!isNil "Z14") then {
removeallweapons Z14;
removeallassigneditems Z14;
removeBackpack Z14;
removeVest Z14;
removeHeadgear Z14;
removeUniform Z14;
removeGoggles Z14;

if (count weapons Z14 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z14) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z14 selectWeapon (_muzzles select 0);
  }
  else {
     Z14 selectWeapon _type;
  };
};
};

if (!isNil "Z13") then {
removeallweapons Z13;
removeallassigneditems Z13;
removeBackpack Z13;
removeVest Z13;
removeHeadgear Z13;
removeUniform Z13;
removeGoggles Z13;

if (count weapons Z13 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z13) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z13 selectWeapon (_muzzles select 0);
  }
  else {
     Z13 selectWeapon _type;
  };
};
};

if (!isNil "W1") then {
removeallweapons W1;
removeallassigneditems W1;
removeBackpack W1;
removeVest W1;
removeHeadgear W1;
removeUniform W1;
removeGoggles W1;

if (count weapons W1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons W1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     W1 selectWeapon (_muzzles select 0);
  }
  else {
     W1 selectWeapon _type;
  };
};
};

if (!isNil "Z8") then {
removeallweapons Z8;
removeallassigneditems Z8;
removeBackpack Z8;
removeVest Z8;
removeHeadgear Z8;
removeUniform Z8;
removeGoggles Z8;

if (count weapons Z8 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z8) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z8 selectWeapon (_muzzles select 0);
  }
  else {
     Z8 selectWeapon _type;
  };
};
};

if (!isNil "Z6") then {
removeallweapons Z6;
removeallassigneditems Z6;
removeBackpack Z6;
removeVest Z6;
removeHeadgear Z6;
removeUniform Z6;
removeGoggles Z6;

if (count weapons Z6 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z6) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z6 selectWeapon (_muzzles select 0);
  }
  else {
     Z6 selectWeapon _type;
  };
};
};

if (!isNil "Z7") then {
removeallweapons Z7;
removeallassigneditems Z7;
removeBackpack Z7;
removeVest Z7;
removeHeadgear Z7;
removeUniform Z7;
removeGoggles Z7;

if (count weapons Z7 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z7) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z7 selectWeapon (_muzzles select 0);
  }
  else {
     Z7 selectWeapon _type;
  };
};
};

if (!isNil "Z9") then {
removeallweapons Z9;
removeallassigneditems Z9;
removeBackpack Z9;
removeVest Z9;
removeHeadgear Z9;
removeUniform Z9;
removeGoggles Z9;

if (count weapons Z9 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z9) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z9 selectWeapon (_muzzles select 0);
  }
  else {
     Z9 selectWeapon _type;
  };
};
};

if (!isNil "Z10") then {
removeallweapons Z10;
removeallassigneditems Z10;
removeBackpack Z10;
removeVest Z10;
removeHeadgear Z10;
removeUniform Z10;
removeGoggles Z10;

if (count weapons Z10 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z10) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z10 selectWeapon (_muzzles select 0);
  }
  else {
     Z10 selectWeapon _type;
  };
};
};

if (!isNil "euro") then {
removeallweapons euro;
removeallassigneditems euro;
removeBackpack euro;
removeVest euro;
removeHeadgear euro;
removeUniform euro;
removeGoggles euro;

if (count weapons euro > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons euro) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     euro selectWeapon (_muzzles select 0);
  }
  else {
     euro selectWeapon _type;
  };
};
};

if (!isNil "Z19") then {
removeallweapons Z19;
removeallassigneditems Z19;
removeBackpack Z19;
removeVest Z19;
removeHeadgear Z19;
removeUniform Z19;
removeGoggles Z19;

if (count weapons Z19 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z19) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z19 selectWeapon (_muzzles select 0);
  }
  else {
     Z19 selectWeapon _type;
  };
};
};

if (!isNil "Z22") then {
removeallweapons Z22;
removeallassigneditems Z22;
removeBackpack Z22;
removeVest Z22;
removeHeadgear Z22;
removeUniform Z22;
removeGoggles Z22;

if (count weapons Z22 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z22) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z22 selectWeapon (_muzzles select 0);
  }
  else {
     Z22 selectWeapon _type;
  };
};
};

if (!isNil "Z24") then {
removeallweapons Z24;
removeallassigneditems Z24;
removeBackpack Z24;
removeVest Z24;
removeHeadgear Z24;
removeUniform Z24;
removeGoggles Z24;

if (count weapons Z24 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z24) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z24 selectWeapon (_muzzles select 0);
  }
  else {
     Z24 selectWeapon _type;
  };
};
};

if (!isNil "Z25") then {
removeallweapons Z25;
removeallassigneditems Z25;
removeBackpack Z25;
removeVest Z25;
removeHeadgear Z25;
removeUniform Z25;
removeGoggles Z25;

if (count weapons Z25 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z25) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z25 selectWeapon (_muzzles select 0);
  }
  else {
     Z25 selectWeapon _type;
  };
};
};

if (!isNil "Z26") then {
removeallweapons Z26;
removeallassigneditems Z26;
removeBackpack Z26;
removeVest Z26;
removeHeadgear Z26;
removeUniform Z26;
removeGoggles Z26;

if (count weapons Z26 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z26) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z26 selectWeapon (_muzzles select 0);
  }
  else {
     Z26 selectWeapon _type;
  };
};
};

if (!isNil "Z27") then {
removeallweapons Z27;
removeallassigneditems Z27;
removeBackpack Z27;
removeVest Z27;
removeHeadgear Z27;
removeUniform Z27;
removeGoggles Z27;

if (count weapons Z27 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z27) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z27 selectWeapon (_muzzles select 0);
  }
  else {
     Z27 selectWeapon _type;
  };
};
};

if (!isNil "Z28") then {
removeallweapons Z28;
removeallassigneditems Z28;
removeBackpack Z28;
removeVest Z28;
removeHeadgear Z28;
removeUniform Z28;
removeGoggles Z28;

if (count weapons Z28 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z28) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z28 selectWeapon (_muzzles select 0);
  }
  else {
     Z28 selectWeapon _type;
  };
};
};

if (!isNil "Z29") then {
removeallweapons Z29;
removeallassigneditems Z29;
removeBackpack Z29;
removeVest Z29;
removeHeadgear Z29;
removeUniform Z29;
removeGoggles Z29;

if (count weapons Z29 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z29) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z29 selectWeapon (_muzzles select 0);
  }
  else {
     Z29 selectWeapon _type;
  };
};
};

if (!isNil "Z20") then {
removeallweapons Z20;
removeallassigneditems Z20;
removeBackpack Z20;
removeVest Z20;
removeHeadgear Z20;
removeUniform Z20;
removeGoggles Z20;

if (count weapons Z20 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z20) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z20 selectWeapon (_muzzles select 0);
  }
  else {
     Z20 selectWeapon _type;
  };
};
};

if (!isNil "Z15") then {
removeallweapons Z15;
removeallassigneditems Z15;
removeBackpack Z15;
removeVest Z15;
removeHeadgear Z15;
removeUniform Z15;
removeGoggles Z15;

if (count weapons Z15 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z15) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z15 selectWeapon (_muzzles select 0);
  }
  else {
     Z15 selectWeapon _type;
  };
};
};

if (!isNil "Z17") then {
removeallweapons Z17;
removeallassigneditems Z17;
removeBackpack Z17;
removeVest Z17;
removeHeadgear Z17;
removeUniform Z17;
removeGoggles Z17;

if (count weapons Z17 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z17) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z17 selectWeapon (_muzzles select 0);
  }
  else {
     Z17 selectWeapon _type;
  };
};
};

if (!isNil "Z18") then {
removeallweapons Z18;
removeallassigneditems Z18;
removeBackpack Z18;
removeVest Z18;
removeHeadgear Z18;
removeUniform Z18;
removeGoggles Z18;

if (count weapons Z18 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z18) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z18 selectWeapon (_muzzles select 0);
  }
  else {
     Z18 selectWeapon _type;
  };
};
};

if (!isNil "Z16") then {
removeallweapons Z16;
removeallassigneditems Z16;
removeBackpack Z16;
removeVest Z16;
removeHeadgear Z16;
removeUniform Z16;
removeGoggles Z16;

if (count weapons Z16 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z16) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z16 selectWeapon (_muzzles select 0);
  }
  else {
     Z16 selectWeapon _type;
  };
};
};

if (!isNil "G1") then {
removeallweapons G1;
removeallassigneditems G1;
removeBackpack G1;
removeVest G1;
removeHeadgear G1;
removeUniform G1;
removeGoggles G1;

if (count weapons G1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons G1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     G1 selectWeapon (_muzzles select 0);
  }
  else {
     G1 selectWeapon _type;
  };
};
};

if (!isNil "Z21") then {
removeallweapons Z21;
removeallassigneditems Z21;
removeBackpack Z21;
removeVest Z21;
removeHeadgear Z21;
removeUniform Z21;
removeGoggles Z21;

if (count weapons Z21 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z21) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z21 selectWeapon (_muzzles select 0);
  }
  else {
     Z21 selectWeapon _type;
  };
};
};

if (!isNil "Z40") then {
removeallweapons Z40;
removeallassigneditems Z40;
removeBackpack Z40;
removeVest Z40;
removeHeadgear Z40;
removeUniform Z40;
removeGoggles Z40;

if (count weapons Z40 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z40) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z40 selectWeapon (_muzzles select 0);
  }
  else {
     Z40 selectWeapon _type;
  };
};
};

if (!isNil "Z23") then {
removeallweapons Z23;
removeallassigneditems Z23;
removeBackpack Z23;
removeVest Z23;
removeHeadgear Z23;
removeUniform Z23;
removeGoggles Z23;

if (count weapons Z23 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z23) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z23 selectWeapon (_muzzles select 0);
  }
  else {
     Z23 selectWeapon _type;
  };
};
};

if (!isNil "Z31") then {
removeallweapons Z31;
removeallassigneditems Z31;
removeBackpack Z31;
removeVest Z31;
removeHeadgear Z31;
removeUniform Z31;
removeGoggles Z31;

if (count weapons Z31 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z31) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z31 selectWeapon (_muzzles select 0);
  }
  else {
     Z31 selectWeapon _type;
  };
};
};

if (!isNil "Z33") then {
removeallweapons Z33;
removeallassigneditems Z33;
removeBackpack Z33;
removeVest Z33;
removeHeadgear Z33;
removeUniform Z33;
removeGoggles Z33;

if (count weapons Z33 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z33) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z33 selectWeapon (_muzzles select 0);
  }
  else {
     Z33 selectWeapon _type;
  };
};
};

if (!isNil "SZ2") then {
removeallweapons SZ2;
removeallassigneditems SZ2;
removeBackpack SZ2;
removeVest SZ2;
removeHeadgear SZ2;
removeUniform SZ2;
removeGoggles SZ2;

if (count weapons SZ2 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons SZ2) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     SZ2 selectWeapon (_muzzles select 0);
  }
  else {
     SZ2 selectWeapon _type;
  };
};
};

if (!isNil "SZ3") then {
removeallweapons SZ3;
removeallassigneditems SZ3;
removeBackpack SZ3;
removeVest SZ3;
removeHeadgear SZ3;
removeUniform SZ3;
removeGoggles SZ3;

if (count weapons SZ3 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons SZ3) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     SZ3 selectWeapon (_muzzles select 0);
  }
  else {
     SZ3 selectWeapon _type;
  };
};
};

if (!isNil "SZ4") then {
removeallweapons SZ4;
removeallassigneditems SZ4;
removeBackpack SZ4;
removeVest SZ4;
removeHeadgear SZ4;
removeUniform SZ4;
removeGoggles SZ4;

if (count weapons SZ4 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons SZ4) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     SZ4 selectWeapon (_muzzles select 0);
  }
  else {
     SZ4 selectWeapon _type;
  };
};
};

if (!isNil "SZ5") then {
removeallweapons SZ5;
removeallassigneditems SZ5;
removeBackpack SZ5;
removeVest SZ5;
removeHeadgear SZ5;
removeUniform SZ5;
removeGoggles SZ5;

if (count weapons SZ5 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons SZ5) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     SZ5 selectWeapon (_muzzles select 0);
  }
  else {
     SZ5 selectWeapon _type;
  };
};
};

if (!isNil "Z30") then {
removeallweapons Z30;
removeallassigneditems Z30;
removeBackpack Z30;
removeVest Z30;
removeHeadgear Z30;
removeUniform Z30;
removeGoggles Z30;

if (count weapons Z30 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z30) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z30 selectWeapon (_muzzles select 0);
  }
  else {
     Z30 selectWeapon _type;
  };
};
};

if (!isNil "Z35") then {
removeallweapons Z35;
removeallassigneditems Z35;
removeBackpack Z35;
removeVest Z35;
removeHeadgear Z35;
removeUniform Z35;
removeGoggles Z35;

if (count weapons Z35 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z35) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z35 selectWeapon (_muzzles select 0);
  }
  else {
     Z35 selectWeapon _type;
  };
};
};

if (!isNil "Z36") then {
removeallweapons Z36;
removeallassigneditems Z36;
removeBackpack Z36;
removeVest Z36;
removeHeadgear Z36;
removeUniform Z36;
removeGoggles Z36;

if (count weapons Z36 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z36) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z36 selectWeapon (_muzzles select 0);
  }
  else {
     Z36 selectWeapon _type;
  };
};
};

if (!isNil "Z38") then {
removeallweapons Z38;
removeallassigneditems Z38;
removeBackpack Z38;
removeVest Z38;
removeHeadgear Z38;
removeUniform Z38;
removeGoggles Z38;

if (count weapons Z38 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z38) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z38 selectWeapon (_muzzles select 0);
  }
  else {
     Z38 selectWeapon _type;
  };
};
};

if (!isNil "Z39") then {
removeallweapons Z39;
removeallassigneditems Z39;
removeBackpack Z39;
removeVest Z39;
removeHeadgear Z39;
removeUniform Z39;
removeGoggles Z39;

if (count weapons Z39 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z39) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z39 selectWeapon (_muzzles select 0);
  }
  else {
     Z39 selectWeapon _type;
  };
};
};

if (!isNil "Z34") then {
removeallweapons Z34;
removeallassigneditems Z34;
removeBackpack Z34;
removeVest Z34;
removeHeadgear Z34;
removeUniform Z34;
removeGoggles Z34;

if (count weapons Z34 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z34) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z34 selectWeapon (_muzzles select 0);
  }
  else {
     Z34 selectWeapon _type;
  };
};
};

if (!isNil "Z37") then {
removeallweapons Z37;
removeallassigneditems Z37;
removeBackpack Z37;
removeVest Z37;
removeHeadgear Z37;
removeUniform Z37;
removeGoggles Z37;

if (count weapons Z37 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z37) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z37 selectWeapon (_muzzles select 0);
  }
  else {
     Z37 selectWeapon _type;
  };
};
};

if (!isNil "Z32") then {
removeallweapons Z32;
removeallassigneditems Z32;
removeBackpack Z32;
removeVest Z32;
removeHeadgear Z32;
removeUniform Z32;
removeGoggles Z32;

if (count weapons Z32 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Z32) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Z32 selectWeapon (_muzzles select 0);
  }
  else {
     Z32 selectWeapon _type;
  };
};
};

if (!isNil "IED_1") then {
removeallweapons IED_1;
removeallassigneditems IED_1;
removeBackpack IED_1;
removeVest IED_1;
removeHeadgear IED_1;
removeUniform IED_1;
removeGoggles IED_1;

if (count weapons IED_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons IED_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     IED_1 selectWeapon (_muzzles select 0);
  }
  else {
     IED_1 selectWeapon _type;
  };
};
};

if (!isNil "kill") then {
removeallweapons kill;
removeallassigneditems kill;
removeBackpack kill;
removeVest kill;
removeHeadgear kill;
removeUniform kill;
removeGoggles kill;

if (count weapons kill > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons kill) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     kill selectWeapon (_muzzles select 0);
  }
  else {
     kill selectWeapon _type;
  };
};
};

if (!isNil "bundeswehr") then {
removeallweapons bundeswehr;
removeallassigneditems bundeswehr;
removeBackpack bundeswehr;
removeVest bundeswehr;
removeHeadgear bundeswehr;
removeUniform bundeswehr;
removeGoggles bundeswehr;

if (count weapons bundeswehr > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons bundeswehr) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     bundeswehr selectWeapon (_muzzles select 0);
  }
  else {
     bundeswehr selectWeapon _type;
  };
};
};

if (!isNil "arti") then {
removeallweapons arti;
removeallassigneditems arti;
removeBackpack arti;
removeVest arti;
removeHeadgear arti;
removeUniform arti;
removeGoggles arti;

if (count weapons arti > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons arti) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     arti selectWeapon (_muzzles select 0);
  }
  else {
     arti selectWeapon _type;
  };
};
};

