/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Sat Sep 27 14:04:34 CEST 2014
* Mission file name: TrUebPl.Chernarus
* Mission name: TrUebPl.Chernarus
* Required mods:
* + ArmA 3
* + AGM
* + RQ-11B Raven
* + ACRE
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//Empty, nothing to do. unit IED
//Empty, nothing to do. unit marine

/**
* Loadout for soldiers units
*/

if (!isNil "s1") then {
	if (player == s1) exitwith {
removeallweapons s1;
removeallassigneditems s1;
removeBackpack s1;
removeVest s1;
removeHeadgear s1;
removeUniform s1;
removeGoggles s1;

if (count weapons s1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons s1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     s1 selectWeapon (_muzzles select 0);
  }
  else {
     s1 selectWeapon _type;
  };
};
	};
};

if (!isNil "s2") then {
	if (player == s2) exitwith {
removeallweapons s2;
removeallassigneditems s2;
removeBackpack s2;
removeVest s2;
removeHeadgear s2;
removeUniform s2;
removeGoggles s2;

if (count weapons s2 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons s2) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     s2 selectWeapon (_muzzles select 0);
  }
  else {
     s2 selectWeapon _type;
  };
};
	};
};

if (!isNil "s3") then {
	if (player == s3) exitwith {
removeallweapons s3;
removeallassigneditems s3;
removeBackpack s3;
removeVest s3;
removeHeadgear s3;
removeUniform s3;
removeGoggles s3;

if (count weapons s3 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons s3) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     s3 selectWeapon (_muzzles select 0);
  }
  else {
     s3 selectWeapon _type;
  };
};
	};
};

if (!isNil "s4") then {
	if (player == s4) exitwith {
removeallweapons s4;
removeallassigneditems s4;
removeBackpack s4;
removeVest s4;
removeHeadgear s4;
removeUniform s4;
removeGoggles s4;

if (count weapons s4 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons s4) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     s4 selectWeapon (_muzzles select 0);
  }
  else {
     s4 selectWeapon _type;
  };
};
	};
};

if (!isNil "s5") then {
	if (player == s5) exitwith {
removeallweapons s5;
removeallassigneditems s5;
removeBackpack s5;
removeVest s5;
removeHeadgear s5;
removeUniform s5;
removeGoggles s5;

if (count weapons s5 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons s5) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     s5 selectWeapon (_muzzles select 0);
  }
  else {
     s5 selectWeapon _type;
  };
};
	};
};

if (!isNil "s6") then {
	if (player == s6) exitwith {
removeallweapons s6;
removeallassigneditems s6;
removeBackpack s6;
removeVest s6;
removeHeadgear s6;
removeUniform s6;
removeGoggles s6;

if (count weapons s6 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons s6) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     s6 selectWeapon (_muzzles select 0);
  }
  else {
     s6 selectWeapon _type;
  };
};
	};
};

if (!isNil "s7") then {
	if (player == s7) exitwith {
removeallweapons s7;
removeallassigneditems s7;
removeBackpack s7;
removeVest s7;
removeHeadgear s7;
removeUniform s7;
removeGoggles s7;

if (count weapons s7 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons s7) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     s7 selectWeapon (_muzzles select 0);
  }
  else {
     s7 selectWeapon _type;
  };
};
	};
};

if (!isNil "s8") then {
	if (player == s8) exitwith {
removeallweapons s8;
removeallassigneditems s8;
removeBackpack s8;
removeVest s8;
removeHeadgear s8;
removeUniform s8;
removeGoggles s8;

if (count weapons s8 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons s8) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     s8 selectWeapon (_muzzles select 0);
  }
  else {
     s8 selectWeapon _type;
  };
};
	};
};

