leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.

_igiload = execVM "IgiLoad\IgiLoadInit.sqf";

//Syssi Sicherheit
if(isServer) then {
	[]execVM "scripts\syssi.sqf";
};
